### PR TITLE
Numpy111 migration

### PR DESCRIPTION
**Pull request by hmaarrfk**
These tests will fail, but I think it is best to selectively skip the test that will.

Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
this is probably going to need a build number bump because it is likely using newer versions of openblas or something.

**Comment by hmaarrfk** [comment]
might need: https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/196 to render correctly.

**Comment by hmaarrfk** [comment]
pccle error

```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/conda_build/environ.py", line 749, in get_install_actions
    actions = install_actions(prefix, index, specs, force=True)
  File "/opt/conda/lib/python3.7/site-packages/conda/common/io.py", line 85, in decorated
    return f(*args, **kwds)
  File "/opt/conda/lib/python3.7/site-packages/conda/plan.py", line 473, in install_actions
    txn = solver.solve_for_transaction(prune=prune, ignore_pinned=not pinned)
  File "/opt/conda/lib/python3.7/site-packages/conda/core/solve.py", line 107, in solve_for_transaction
    force_remove, force_reinstall)
  File "/opt/conda/lib/python3.7/site-packages/conda/core/solve.py", line 145, in solve_for_diff
    force_remove)
  File "/opt/conda/lib/python3.7/site-packages/conda/core/solve.py", line 242, in solve_final_state
    ssc = self._run_sat(ssc)
  File "/opt/conda/lib/python3.7/site-packages/conda/common/io.py", line 85, in decorated
    return f(*args, **kwds)
  File "/opt/conda/lib/python3.7/site-packages/conda/core/solve.py", line 500, in _run_sat
    ssc.solution_precs = ssc.r.solve(tuple(final_environment_specs))
  File "/opt/conda/lib/python3.7/site-packages/conda/common/io.py", line 85, in decorated
    return f(*args, **kwds)
  File "/opt/conda/lib/python3.7/site-packages/conda/resolve.py", line 1047, in solve
    self.find_conflicts(specs)
  File "/opt/conda/lib/python3.7/site-packages/conda/resolve.py", line 316, in find_conflicts
    raise UnsatisfiableError(bad_deps)
conda.exceptions.UnsatisfiableError: The following specifications were found to be in conflict:
  - libgfortran-ng[version='>=8,<9.0a0']
  - openblas=0.3.3 -> libopenblas==0.3.3=h5a2b251_3 -> libgfortran-ng[version='>=7,<8.0a0']
Use "conda search <package> --info" to see the dependencies for each package.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 442, in main
    execute(sys.argv[1:])
  File "/opt/conda/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 433, in execute
    verify=args.verify, variants=args.variants)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/api.py", line 207, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 2300, in build_tree
    notest=notest,
  File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 1265, in build
    output_metas = expand_outputs([(m, need_source_download, need_reparse_in_env)])
  File "/opt/conda/lib/python3.7/site-packages/conda_build/render.py", line 706, in expand_outputs
    for (output_dict, m) in _m.get_output_metadata_set(permit_unsatisfiable_variants=False):
  File "/opt/conda/lib/python3.7/site-packages/conda_build/metadata.py", line 2013, in get_output_metadata_set
    bypass_env_check=bypass_env_check)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/metadata.py", line 714, in finalize_outputs_pass
    permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/render.py", line 489, in finalize_metadata
    exclude_pattern)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/render.py", line 384, in add_upstream_pins
    permit_unsatisfiable_variants, exclude_pattern)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/render.py", line 350, in _read_upstream_pin_files
    permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/render.py", line 136, in get_env_dependencies
    channel_urls=tuple(m.config.channel_urls))
  File "/opt/conda/lib/python3.7/site-packages/conda_build/environ.py", line 751, in get_install_actions
    raise DependencyNeedsBuildingError(exc, subdir=subdir)
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-ppc64le: {"libgfortran-ng[version='>=8,<9.0a0']", "libgfortran-ng[version='>=7,<8.0a0']"}
##[error]Bash exited with code '1'.
```

**Comment by hmaarrfk** [comment]
regular linux seems to be broken:

```

/bin/sh: svnversion: command not found
/bin/sh: svnversion: command not found
F2PY Version 2
lapack_opt_info:
openblas_lapack_info:
customize UnixCCompiler
Traceback (most recent call last):
  File "setup.py", line 386, in <module>
    setup_package()
  File "setup.py", line 378, in setup_package
    setup(**metadata)
  File "/home/conda/feedstock_root/build_artifacts/numpy_1551033104783/work/numpy/distutils/core.py", line 135, in setup
    config = configuration()
  File "setup.py", line 161, in configuration
    config.add_subpackage('numpy')
  File "/home/conda/feedstock_root/build_artifacts/numpy_1551033104783/work/numpy/distutils/misc_util.py", line 1000, in add_subpackage
    caller_level = 2)
  File "/home/conda/feedstock_root/build_artifacts/numpy_1551033104783/work/numpy/distutils/misc_util.py", line 969, in get_subpackage
    caller_level = caller_level + 1)
  File "/home/conda/feedstock_root/build_artifacts/numpy_1551033104783/work/numpy/distutils/misc_util.py", line 906, in _get_configuration_from_setup_py
    config = setup_module.configuration(*args)
  File "numpy/setup.py", line 16, in configuration
    config.add_subpackage('linalg')
  File "/home/conda/feedstock_root/build_artifacts/numpy_1551033104783/work/numpy/distutils/misc_util.py", line 1000, in add_subpackage
    caller_level = 2)
  File "/home/conda/feedstock_root/build_artifacts/numpy_1551033104783/work/numpy/distutils/misc_util.py", line 969, in get_subpackage
    caller_level = caller_level + 1)
  File "/home/conda/feedstock_root/build_artifacts/numpy_1551033104783/work/numpy/distutils/misc_util.py", line 906, in _get_configuration_from_setup_py
    config = setup_module.configuration(*args)
  File "numpy/linalg/setup.py", line 26, in configuration
    lapack_info = get_info('lapack_opt', 0)  # and {}
  File "/home/conda/feedstock_root/build_artifacts/numpy_1551033104783/work/numpy/distutils/system_info.py", line 378, in get_info
    return cl().get_info(notfound_action)
  File "/home/conda/feedstock_root/build_artifacts/numpy_1551033104783/work/numpy/distutils/system_info.py", line 566, in get_info
    self.calc_info()
  File "/home/conda/feedstock_root/build_artifacts/numpy_1551033104783/work/numpy/distutils/system_info.py", line 1472, in calc_info
    openblas_info = get_info('openblas_lapack')
  File "/home/conda/feedstock_root/build_artifacts/numpy_1551033104783/work/numpy/distutils/system_info.py", line 378, in get_info
    return cl().get_info(notfound_action)
  File "/home/conda/feedstock_root/build_artifacts/numpy_1551033104783/work/numpy/distutils/system_info.py", line 566, in get_info
    self.calc_info()
  File "/home/conda/feedstock_root/build_artifacts/numpy_1551033104783/work/numpy/distutils/system_info.py", line 1745, in calc_info
    if not self.check_embedded_lapack(info):
  File "/home/conda/feedstock_root/build_artifacts/numpy_1551033104783/work/numpy/distutils/system_info.py", line 1780, in check_embedded_lapack
    obj = c.compile([src], output_dir=tmpdir)
  File "/home/conda/feedstock_root/build_artifacts/numpy_1551033104783/work/numpy/distutils/ccompiler.py", line 27, in <lambda>
    m = lambda self, *args, **kw: func(self, *args, **kw)
  File "/home/conda/feedstock_root/build_artifacts/numpy_1551033104783/work/numpy/distutils/ccompiler.py", line 169, in CCompiler_compile
    from numpy.distutils.fcompiler import (FCompiler, is_f_file,
  File "/home/conda/feedstock_root/build_artifacts/numpy_1551033104783/work/numpy/distutils/fcompiler/__init__.py", line 45, in <module>
    from .environment import EnvironmentConfig
ModuleNotFoundError: No module named 'numpy.distutils.fcompiler.environment'
Traceback (most recent call last):
  File "/opt/conda/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 456, in main
    execute(sys.argv[1:])
  File "/opt/conda/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 447, in execute
    verify=args.verify, variants=args.variants)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/api.py", line 208, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 2314, in build_tree
    notest=notest,
  File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 1477, in build
    cwd=src_dir, stats=build_stats)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/utils.py", line 374, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/utils.py", line 354, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-e', '/home/conda/feedstock_root/build_artifacts/numpy_1551033104783/work/conda_build.sh']' returned non-zero exit status 1.
Exited with code 1
```

**Comment by hmaarrfk** [comment]
@jjhelmus @mariusvniekerk I cleaned up the PR making it cherry-pickable. though PPC builds are still an issue.

Also, if anybody could explain why I need:
https://github.com/conda-forge/numpy-feedstock/pull/132/commits/5ecfdd7667bd29bb5646b47639d99dd7b71c1c7a

It would be appreciated.

**Comment by hmaarrfk** [comment]
@mariusvniekerk how did you generate the travis for ppc64le? Are you on your dev version?

**Comment by mariusvniekerk** [comment]
yes

**Comment by hmaarrfk** [comment]
lets see what happens.

**Comment by hmaarrfk** [comment]
Nice. This just seems to be a little bug with the repr test

**Comment by hmaarrfk** [comment]
Wootttt!! ppc64le just passed.

@mariusvniekerk will this upload the PPC64LE packages?

@jjhelmus final review?

**Comment by jjhelmus** [comment]
LGTM

**Comment by jjhelmus** [comment]
@hmaarrfk Thanks for all your hard work seeing this though!  I am certain there are many people, me included, that are excited to see numpy packages available for conda on these platforms.

**Pull request merged**
