### PR TITLE
Release 1.15.0

### PR DESCRIPTION
**Pull request by jakirkham**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jakirkham** [comment]
@conda-forge-admin, please re-render.

**Comment by jakirkham** [comment]
Windows seems to fail, but am not sure why. @isuruf, any ideas?

**Comment by isuruf** [comment]
Maybe we need something like, https://github.com/AnacondaRecipes/numpy-feedstock/commit/1c7ecc5e31ec67cc93f48baefddb7d0a940fe929

cc @msarahan

**Comment by jakirkham** [comment]
Interesting. Was this a change in NumPy or a change on AppVeyor perhaps?

**Comment by jakirkham** [comment]
Done in PR ( https://github.com/conda-forge/numpy-feedstock/pull/96 ).

**Pull request closed without merging**
