### PR TITLE
Rebuild numpy 1.16 for python 3.9

### PR DESCRIPTION
**Pull request by ocefpaf**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ocefpaf** [comment]
Not sure if this is better than just bumping our pin.

**Comment by ocefpaf** [comment]
@isuruf do you think it is worth pursing this or should we just close it?

**Comment by isuruf** [comment]
I think we should just close it.

**Comment by rgommers** [comment]
NumPy 1.19.2 is the first version that supports Python 3.9. Agreed with closing this.

**Comment by isuruf** [comment]
Thanks @rgommers, @ocefpaf

**Pull request closed without merging**
