### PR TITLE
Add PyPy build

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by isuruf** [comment]
PyPy is using the correct compiler when compiling sources, but uses the wrong one when linking.

cc @mattip

**Comment by isuruf** [comment]
Fixed in https://github.com/conda-forge/pypy3.6-feedstock/pull/14

@mattip, @rgommers, do you know what's the oldest version of numpy that supports PyPy3.6 7.3.0?

**Comment by mattip** [comment]
I think 1.16, but I would start with only creating a feedstock for the latest release 1.18. If someone complains maybe you can consider 1.17.

**Comment by isuruf** [comment]
We are building downstream projects with 1.14 with cpython. I'm wondering whether we should bump that to 1.16 on all platforms and build 1.16 with PyPy as well to make it uniform.

**Comment by rgommers** [comment]
Hmm, 1.16.0 is only one year old, so I would prefer to keep CPython unchanged. PyPy is its own thing anyway, so I don't see an issue with building that against 1.16 while CPython builds use 1.14

**Comment by isuruf** [comment]
Okay. In that case I'll go with 1.18 on PyPy and 1.14 on CPython.

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Comment by isuruf** [comment]
@tylerjereddy, @mattip, @rgommers, 96 errors on aarch64 with the PyPy build and 0 with Cpython. Is that expected>

**Comment by isuruf** [comment]
Not sure what's going on at
```
_____________ ERROR collecting distutils/tests/test_system_info.py _____________
../_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python3.6/site-packages/numpy/distutils/tests/test_system_info.py:89: in <module>
    HAVE_COMPILER = have_compiler()
../_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python3.6/site-packages/numpy/distutils/tests/test_system_info.py:69: in have_compiler
    compiler = customized_ccompiler()
../_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python3.6/site-packages/numpy/distutils/__init__.py:52: in customized_ccompiler
    c.customize('')
../_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python3.6/site-packages/numpy/distutils/ccompiler.py:92: in <lambda>
    m = lambda self, *args, **kw: func(self, *args, **kw)
../_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python3.6/site-packages/numpy/distutils/ccompiler.py:544: in CCompiler_customize
    extra_preargs=['-MMD', '-MF', fn + '.d'])
../_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python3.6/site-packages/numpy/distutils/ccompiler.py:92: in <lambda>
    m = lambda self, *args, **kw: func(self, *args, **kw)
../_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python3.6/site-packages/numpy/distutils/ccompiler.py:270: in CCompiler_compile
    jobs = get_num_build_jobs()
../_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python3.6/site-packages/numpy/distutils/misc_util.py:97: in get_num_build_jobs
    from numpy.distutils.core import get_distribution
../_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python3.6/site-packages/numpy/distutils/core.py:26: in <module>
    from numpy.distutils.command import config, config_compiler, \
../_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python3.6/site-packages/numpy/distutils/command/build_src.py:25: in <module>
    from numpy.distutils.conv_template import process_file as process_c_file
../_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python3.6/site-packages/numpy/distutils/conv_template.py:144: in <module>
    parenrep = re.compile(r"[(]([^)]*)[)]\*(\d+)")
../_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib-python/3/re.py:233: in compile
    return _compile(pattern, flags)
../_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib-python/3/re.py:301: in _compile
    p = sre_compile.compile(pattern, flags)
../_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib-python/3/sre_compile.py:570: in compile
    code = _code(p, flags)
../_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib-python/3/sre_compile.py:555: in _code
    _compile(code, p.data, flags)
../_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib-python/3/sre_compile.py:146: in _compile
    _compile(code, p, (flags | add_flags) & ~del_flags)
../_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib-python/3/sre_compile.py:124: in _compile
    emit(av[0])
E   IndexError: tuple index out of range
```

**Comment by rgommers** [comment]
> 96 errors on aarch64 with the PyPy

I have no idea if that's even supposed to work (@mattip ?). We only test PyPy on Linux in NumPy CI.

**Comment by isuruf** [comment]
It's a PyPy error. I opened https://foss.heptapod.net/pypy/pypy/issues/3188

**Comment by isuruf** [comment]
Opened a couple of issues on numpy tracker as well.
https://github.com/numpy/numpy/issues/15755
https://github.com/numpy/numpy/issues/15754

**Comment by mattip** [comment]
The first one (a warning from cython) should have been fixed by a commit to cython from 12/2018, xref cython/cython#3431.

**Comment by isuruf** [comment]
Done in https://github.com/conda-forge/numpy-feedstock/pull/186

**Pull request closed without merging**
