### PR TITLE
Use Drone for native aarch64 builds

### PR DESCRIPTION
**Pull request by jmreicha**
Rendered using the (WIP) [drone branch](https://github.com/conda-forge/conda-smithy/pull/1069) of conda-smithy for adding native aarch64 builds.

Checklist

* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by isuruf** [comment]
Can you open a new PR to check if drone picks it up?

**Comment by jmreicha** [comment]
@isuruf I think we will need to work out how to get Drone to pick this up, unless you have manually set things up on that side of things already.

Another other option for now is I can just do a manual Drone build with my personal account.

**Comment by isuruf** [comment]
I manually activated https://cloud.drone.io/conda-forge/numpy-feedstock

**Pull request closed without merging**
