### PR TITLE
Test Drone for native aarch64 builds

### PR DESCRIPTION
**Pull request by jmreicha**
Rendered using the (WIP) [drone branch](https://github.com/conda-forge/conda-smithy/pull/1069) of conda-smithy for adding native aarch64 builds.

Checklist

* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by isuruf** [comment]
There's only one job running on drone. (python3.7)

**Comment by jmreicha** [comment]
Guess I don't have the anchors worked out yet 😂

**Comment by jmreicha** [comment]
Feel free to update if you see something obvious.

**Comment by isuruf** [comment]
Can you try without anchors? Does it work?

**Comment by jmreicha** [comment]
It should, I'll give it a try.

**Comment by isuruf** [comment]
looks like jsonnet doesn't work and anchors don't work across builds

**Comment by jmreicha** [comment]
Yeah, not sure of a good workaround but will keep looking at it 😢 

Did you see the build failures from build #3?  Are those expected?

**Comment by hmaarrfk** [comment]
These @kind@ errors were found to be a bug in the gcc compiler that is used for aarch64.

You should look at the meta.yaml file https://github.com/conda-forge/numpy-feedstock/pull/138/files#diff-e178b687b10a71a3348107ae3154e44c

In the other PR and pull what you need from there. For now, I would avoid the patches since building on a native arch should avoid the need for them.

**Comment by jmreicha** [comment]
Good to know.  This one is mainly to test if Drone builds work, so will probably just wait until those issues get resolved with the other PR first.

**Comment by hmaarrfk** [comment]
I think it would be super interesting if you could pull in the llvm line into drone. I'm mostly curious if the other libraries are correctly compiled. Skipping tests is only OK if we are sure that it is OK to do so.

**Comment by hmaarrfk** [comment]
(sorry I don't have the rights to your repo to push in the same way that isuruf did)

**Comment by jmreicha** [comment]
Added you as a collaborator if you want to try it out.

**Comment by hmaarrfk** [comment]
I guess we need to monitor what happens here: https://cloud.drone.io/conda-forge/numpy-feedstock

**Comment by jmreicha** [comment]
Hrm, it was working the other day.  I wonder if a Drone setting changed.

**Comment by isuruf** [comment]
I changed the configuration file from .drone.yml to .drone.jsonnet. Reverted this change

**Comment by hmaarrfk** [comment]
it seems only your pushes are caught. fun fun :/ especially for difficult builds where many people seem to jump in.

**Comment by hmaarrfk** [comment]
@isuruf beat you to it. I just wanted to test the build. We can go back to different configuration styles, you would need to revert my revert ;)

**Comment by jmreicha** [comment]
@hmaarrfk I also have https://cloud.drone.io/jmreicha/numpy-feedstock/2/1/2 going if you want to test anything.

**Comment by hmaarrfk** [comment]
Seems to be running now. Lets see what happens.

**Comment by hmaarrfk** [comment]
totally needs `pytest-xdist`....

**Comment by hmaarrfk** [comment]
Ok Cool. It seems that this is a known issue in numpy

image

**Comment by hmaarrfk** [comment]
Seems like some garbage collector tests aren't dealing too well with pytest-xdist

**Pull request closed without merging**
