### PR TITLE
Also define entry-point on unix

### PR DESCRIPTION
**Pull request by h-vetinari**
Hopefully addresses #276, but so far only pushing into a dev label.

### CODE REVIEW

**Comment by bnavigator** [comment]
Please also provide f2py3 and f2py3.10 (as variable major.minor)

scikit-build/FindF2PY.cmake looks for the former
https://github.com/scikit-build/scikit-build/blob/2e7ef6af0e03a0677f835ec9aad74e6b669fc8c5/skbuild/resources/cmake/FindF2PY.cmake#L69

**Comment by h-vetinari** [comment]
> Please also provide f2py3 and f2py3.10 (as variable major.minor)
> 
> scikit-build/FindF2PY.cmake looks for the former

That's an issue of scikit-build, IMO. Python 2 is gone for 2.5 years. I can be convinced to add `f2py3`, but I'm very much against the churn of adding the minor versions too. If you need that, you should symlink it in your setup, IMO.

> f2py3 and f2py3.10 are upstream definitions and expected e.g. by https://github.com/scikit-build/scikit-build/blob/master/skbuild/resources/cmake/FindF2PY.cmake#L69

To stop spreading the discussion in different PRs, responding to your [comment](https://github.com/conda-forge/numpy-feedstock/issues/276#issuecomment-1180664904) from #276 - I remain unconvinced. Other maintainers may disagree, and I'll bow to the majority if necessary.

**Comment by bnavigator** [comment]
I can see that the rationale to have cmd3 and cmd3.10 similar to the interpreter executables (python3, python3.10) and pip (pip3, pip3.10) is not applicable to conda environments.

* The ipython feedstock also provides the ipython3 entry point. Same set as upstream
  - https://github.com/conda-forge/ipython-feedstock/blob/bf57b0a3e721fca24306429f5f813b02e59ff05a/recipe/meta.yaml#L24-L26
  - https://github.com/ipython/ipython/blob/359181665fcc65c6ff4d76430348ca27858b0443/setup.cfg#L100-L103
  
* The pip-feedstock provides pip3 but not pip3.10
  - https://github.com/conda-forge/pip-feedstock/blob/bd35665c47f0e76963524e9122ba2e680d6b463b/recipe/meta.yaml#L15-L17
  - https://github.com/pypa/pip/blob/c0fb4bf1ad21d6f764085de132d25f834db1da90/setup.py#L75-L79

**Comment by h-vetinari** [comment]
Ok, happy to draw the line at `f2py3` (i.e. add it). Would you be able to provide a more comprehensive test for `f2py` than just displaying the help text? I'd be happier if we were a bit more thorough about that.

**Comment by bnavigator** [comment]
I think, if you do not want to register the f2py3.minor with conda, you should prevent the installation of it completely by applying the patch:

```
diff --git a/setup.py b/setup.py
index 353b6c096..ed1a38834 100755
--- a/setup.py
+++ b/setup.py
@@ -425,7 +425,6 @@ def setup_package():
         f2py_cmds = [
             'f2py = numpy.f2py.f2py2e:main',
             'f2py%s = numpy.f2py.f2py2e:main' % sys.version_info[:1],
-            'f2py%s.%s = numpy.f2py.f2py2e:main' % sys.version_info[:2],
             ]
 
     cmdclass["sdist"] = sdist_checked
```

Otherwise you risk to end up with an installed `entry_point` which does not have the right shebang.

**Comment by bnavigator** [comment]
> Would you be able to provide a more comprehensive test for `f2py` than just displaying the help text? I'd be happier if we were a bit more thorough about that.

There is the possibility to let it compile something from `numpy/f2py/tests/src`, but I think your recipe explicitly skips all f2py tests because it would pull in a Fortran compiler. (https://github.com/conda-forge/numpy-feedstock/pull/272#issuecomment-1139532951)

**Comment by bnavigator** [comment]
Parse and generate code only:
```
$ f2py -m fibby doc/source/f2py/code/fib1.f 
Reading fortran codes...
        Reading file 'doc/source/f2py/code/fib1.f' (format:fix,strict)
Post-processing...
        Block: fibby
                        Block: FIB
Post-processing (stage 2)...
Building modules...
        Building module "fibby"...
                Constructing wrapper function "FIB"...
                  FIB(A,[N])
        Wrote C/API module "fibby" to file "./fibbymodule.c"
```
Compile:
```
$ f2py -c -m fibby doc/source/f2py/code/fib1.f 
```

**Comment by bnavigator** [comment]
In reply to https://github.com/conda-forge/numpy-feedstock/issues/276#issuecomment-1180676622:

I fired up my windows VM and installed the current numpy from conda-forge.
  * `f2py.bat` exists
  * `f2py.exe` and f2py-script.py also exists which means the exe must have been installed by conda from the entry_points line after the `del %SCRIPTS%\f2py.exe` command in `bld.bat`
  * The `.exe` trumps the `.bat` in cmd and in the PowerShell.

**Comment by h-vetinari** [comment]
> I think, if you do not want to register the f2py3.minor with conda, you should prevent the installation of it completely by applying the patch:

That's a compelling argument, thanks. It's less of a pain to specify the minor entry-points as well, rather than carry a patch.

**Comment by h-vetinari** [comment]
OK, I'm slapping an automerge on this. Would be cool if you could test this once the builds are online after the merge. To do so, you'll have to add the following to `recipe/conda_build_config.yaml` (c.f. e.g. [here](https://github.com/conda-forge/clangdev-feedstock/blob/rc/recipe/conda_build_config.yaml#L17-L18)) and then rerender:

```
channel_sources:
  - conda-forge/label/numpy_dev,conda-forge
```

**Comment by h-vetinari** [comment]
Should be good to go for testing now!

**Comment by bnavigator** [comment]
https://github.com/conda-forge/slycot-feedstock/pull/55

**Comment by bnavigator** [comment]
Bummer: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=535639&view=logs&j=385a3385-ae8b-54d1-9abe-3c614f74cb73&t=a5f9d343-149e-5621-6ab9-f0278009be04&l=406

**Pull request merged**
