### PR TITLE
Python 3.12

### PR DESCRIPTION
**Pull request by h-vetinari**
Mainly to figure out which dependencies are missing; last time we needed pytest, but that got turned noarch in the meantime.

CC @xhochy @pavelzw @0xbe7a

### CODE REVIEW

**Comment by h-vetinari** [comment]
I think the cython builds haven't made it through the CDN yet...

**Comment by xhochy** [comment]
> I think the cython builds haven't made it through the CDN yet...

You only merged `cython=0.29` for Python 3.12. The one on `main` still has to come.

**Comment by xhochy** [comment]
Sorry, outdated with my mails! 🙈

**Comment by 0xbe7a** [comment]
Can you try to rerun the linux_ppc64le_numpy1.26python3.12 build?

**Comment by xhochy** [comment]
> Can you try to rerun the linux_ppc64le_numpy1.26python3.12 build?

Only once the other builds have passed.

**Comment by h-vetinari** [comment]
I'm going to merge this as soon as the x64 builds pass. aarch/ppc take ~2h to build; and the failure on ppc was purely because one package hadn't made it through the CDN yet.

**Pull request merged**
