### PR TITLE
Update to 2.0.1

### PR DESCRIPTION
**Pull request by lpsinger**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by lpsinger** [comment]
@conda-forge-admin, please rerender

**Comment by h-vetinari** [comment]
Thanks for the PR! Not sure why the bot failed to open it -- status page says:

<details>

```
3.00 attempts - bot error ([bot CI job](https://github.com/regro/cf-scripts/actions/runs/10025061166)): main:
Error running migrate-feedstock in container - error VersionMigrationError raised:
"The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!

Please check the URLs in your recipe with version '2.0.1' to make sure they exist!

We also found the following errors:

 - could not hash URL template 'https://github.com/numpy/numpy/releases/download/v{{ version }}{{ dev }}/numpy-{{ version }}{{ dev }}.tar.gz'
"
```

</details>

In any case, this is running into https://github.com/mesonbuild/meson/issues/13403, which hasn't been backported to the vendored meson yet.

**Comment by h-vetinari** [comment]
I've fixed this up in #322; it's based on your PR though, and should show up as merged (AFAIU the way github works). Thanks again!

**Comment by lpsinger** [comment]
> I've fixed this up in #322; it's based on your PR though, which should show up as merged (AFAIU the way github works). Thanks again!

I bow to your superior mastery of the conda-forge arcana. Thank you!

**Comment by h-vetinari** [comment]
Hm, it doesn't work of course if you delete the branch before the other one gets merged. 😅 Based on the fact that 305cb3d0839f90d2ba47f06369478adf9c2cc3dd appears 1:1 on main now, this would have showed up as purple.

**Pull request closed without merging**
