### PR TITLE
Switch PPC to cross-compilation & testing in emulation

### PR DESCRIPTION
**Pull request by h-vetinari**
Trying to go back because travis is unstable (often needs many restarts to run through), and to try QEMU 7.

### CODE REVIEW

**Comment by h-vetinari** [comment]
Finally there's a QEMU issue for this... https://gitlab.com/qemu-project/qemu/-/issues/1086

**Comment by h-vetinari** [comment]
@conda-forge-admin, please rerender

**Comment by h-vetinari** [comment]
@conda-forge/numpy 
Amazing news 🤩 

After literally years of being unable to run the numpy tests for PPC in emulation due to spurious errors (that didn't appear on native hardware), it looks like the recent QEMU 7.2 has finally gotten rid of those issues and we can now treat PPC like aarch here (less reliance on flaky Travis).

Planning to merge this change (plus some minor clean-ups) on Sunday.

CC @conda-forge/core

**Comment by h-vetinari** [comment]
Scipy CI is green as well in emulation 🤯 
https://github.com/conda-forge/scipy-feedstock/pull/225

**Comment by hmaarrfk** [comment]
Just clarifying that qemu 7 is enabled conda forge wide?

**Comment by h-vetinari** [comment]
> Just clarifying that qemu 7 is enabled conda forge wide?

To the best of my understanding, the docker-images [always](https://github.com/conda-forge/docker-images/blob/main/download-qemu-static.sh#L4-L12) download the latest available [qemu-user-static](https://github.com/multiarch/qemu-user-static), at least on the x64 agents (which is where we're running this). It might have changed, but I once double-checked this with the image hashes (in the CI log) against those on docker-hub.

**Pull request merged**
