### PR TITLE
TEST: 1.23.x + blas variants

### PR DESCRIPTION
**Pull request by h-vetinari**
Continuing the analysis from #252, #237, #227 & #196. Should not be merged for the same reasons as #227.

### CODE REVIEW

**Comment by h-vetinari** [comment]
### Update for numpy 1.23

After being [all green](https://github.com/conda-forge/numpy-feedstock/pull/252#issuecomment-1110476411) for 1.22.3, we're still all green for 1.23.0 🥳 (with some small caveats below)

### Notable

- Tried running PPC on azure again (due to new QEMU release), but still running into problems (see #274). Opened an upstream [issue](https://gitlab.com/qemu-project/qemu/-/issues/1086).
- Added (most) optional [test dependencies](https://github.com/numpy/numpy/blob/main/test_requirements.txt) in #272 ([discussion](https://github.com/conda-forge/numpy-feedstock/pull/272#discussion_r904781658)) - now covering even more tests.

### Restrictions

- ppc64le and pypy-on-aarch only run tests with `label='fast'`, not the full test suite
- the following test skips:
```
# https://github.com/numpy/numpy/issues/15243
{% set tests_to_skip = tests_to_skip + " or test_loss_of_precision[complex256]" %}  # [ppc64le]
# Sometimes crashes on travis (needs too much memory); since 1.22.4 it fails for pypy
{% set tests_to_skip = tests_to_skip + " or test_large_archive" %}                  # [(CI == "travis") or ((python_impl == "pypy") and linux)]
# there are some tests that cannot really work in emulation, see e.g. numpy/numpy#20445
{% set tests_to_skip = tests_to_skip + " or Test_ARM_Features" %}                   # [build_platform != target_platform]
# test_new_policy reruns part of test suite; including a CPU feature test that fails in emulation
{% set tests_to_skip = tests_to_skip + " or test_new_policy" %}                     # [build_platform != target_platform]
# flaky refcount-based test; already skipped upstream for win+py39
{% set tests_to_skip = tests_to_skip + " or test_partial_iteration_cleanup" %}      # [osx]
```

### Details

| variant | [before](https://github.com/conda-forge/numpy-feedstock/pull/252#issuecomment-1110476411) | after |
|--------|-------|----|
| linux + ppc (on azure) | test failures due to emulation problems | same (see #274 & [here](https://gitlab.com/qemu-project/qemu/-/issues/1086)) |
| linux + ppc (on travis) | fine (with 2 test skips) | same |

--------------------

| lib | [before](https://github.com/conda-forge/numpy-feedstock/pull/252#issuecomment-1110476411) | after | updated<br/>version | updated<br/>build |
|--------|-------|----|-|-|
| `numpy` | `1.22.3` | `1.23.0` | X | |
| `libblas` | `3.9.0-14` | `3.9.0-15` | | X |
| `blis` | `0.9.0-0` | `0.9.0-0` | | |
| `openblas` | `0.3.20-pthreads-0` | `0.3.20-pthreads-0` | | |
| `mkl` | `2022.0.1-803` | `2022.1.0-915` | X | |
| `netlib` | `3.9.0-5` | `3.9.0-5` | | |
| `pypy` | `7.3.9-2`  | `7.3.9-2` | | |
| [`qemu-user-static`](https://github.com/multiarch/qemu-user-static) | `6.1.0-8` | `7.0.0-7` | X | |

---------------

| variant | accelerate | blis | mkl | netlib | openblas | sum* | 
|--------|------------|----|-----|-------|-----------|-------|
| linux / x86 | ➖ | ✔️ | ✔️ | ✔️ | ✔️ | - | 
| linux / aarch | ➖ | ➖ | ➖ | ✔️ | ✔️ | - | 
| linux / ppc64le | ➖ | ➖ | ➖ | ✔️ | ✔️ | - |
| osx / arm | ✔️ | ➖ | ➖ | ✔️ | ✔️ | - |
| osx / x86 | ✔️ | ✔️ | ✔️ | ✔️ | ✔️ | - |
| win / x86 | ➖ | ✔️ | ✔️ | ✔️ | ✔️ | - |
| sum* | - | - | - | - | - | - |

`*` sum of Failures (out of a total of 94 CI combinations being tested)

Build logs:
[Azure](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=526210&view=results)
[Travis](https://app.travis-ci.com/github/conda-forge/numpy-feedstock/builds/252355753)

**Comment by rgommers** [comment]
Looks great!

**Comment by h-vetinari** [comment]
### Update for numpy 1.23.5

After being [all green](https://github.com/conda-forge/numpy-feedstock/pull/273#issuecomment-1164975678) for 1.23.0, we're still all green for 1.23.5 🥳 (with some small caveats below)

### Notable

- It looks like the new QEMU 7.2.0 might have finally solved our emulation problems with PPC (see #274), and thus the flakiness of Travis. 🤩 🥳 🚀 
Xref also this [issue](https://gitlab.com/qemu-project/qemu/-/issues/1086).

### Restrictions

- ppc64le and pypy-on-aarch only run tests with `label='fast'`, not the full test suite
- the following test skips:
```
# https://github.com/numpy/numpy/issues/15243
{% set tests_to_skip = tests_to_skip + " or test_loss_of_precision[complex256]" %}  # [ppc64le]
# Sometimes crashes on travis (needs too much memory); since 1.22.4 it fails for pypy
{% set tests_to_skip = tests_to_skip + " or test_large_archive" %}                  # [(CI == "travis") or ((python_impl == "pypy") and linux)]
# there are some tests that cannot really work in emulation, see e.g. numpy/numpy#20445
{% set tests_to_skip = tests_to_skip + " or Test_ARM_Features" %}                   # [build_platform != target_platform]
# test_new_policy reruns part of test suite; including a CPU feature test that fails in emulation
{% set tests_to_skip = tests_to_skip + " or test_new_policy" %}                     # [build_platform != target_platform]
# flaky refcount-based test; already skipped upstream for win+py39
{% set tests_to_skip = tests_to_skip + " or test_partial_iteration_cleanup" %}      # [osx]
```

### Details

| variant | [before](https://github.com/conda-forge/numpy-feedstock/pull/273#issuecomment-1164975678) | after |
|--------|-------|----|
| linux + ppc (on azure) | test failures due to emulation problems | looks like #274 is now working 🥳 |
| linux + ppc (on travis) | fine (with 2 test skips) | same |

--------------------

| lib | [before](https://github.com/conda-forge/numpy-feedstock/pull/273#issuecomment-1164975678) | after | updated<br/>version | updated<br/>build |
|--------|-------|----|-|-|
| `numpy` | `1.23.0` | `1.23.5` | X | |
| `libblas` | `3.9.0-15` | `3.9.0-16` | | X |
| `blis` | `0.9.0-0` | `0.9.0-0` | | |
| `openblas` | `0.3.20-pthreads-0` | `0.3.21-pthreads-3` | X | |
| `mkl` | `2022.1.0-915` | `2022.1.0-915` | | |
| `netlib` | `3.9.0-5` | `3.9.0-5` | | |
| `pypy` | `7.3.9-2`  | `7.3.9-7` | | X |
| [`qemu-user-static`](https://github.com/multiarch/qemu-user-static) | `7.0.0-7` | `7.2.0-1` | X | |

---------------

| variant | accelerate | blis | mkl | netlib | openblas | sum* | 
|--------|------------|----|-----|-------|-----------|-------|
| linux / x86 | ➖ | ✔️ | ✔️ | ✔️ | ✔️ | - | 
| linux / aarch | ➖ | ➖ | ➖ | ✔️ | ✔️ | - | 
| linux / ppc64le | ➖ | ➖ | ➖ | ✔️ | ✔️ | - |
| osx / arm | ✔️ | ➖ | ➖ | ✔️ | ✔️ | - |
| osx / x86 | ✔️ | ✔️ | ✔️ | ✔️ | ✔️ | - |
| win / x86 | ➖ | ✔️ | ✔️ | ✔️ | ✔️ | - |
| sum* | - | - | - | - | - | - |

`*` sum of Failures (out of a total of 114 CI combinations being tested)

Build logs:
[Azure](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=648268&view=results)
[Travis](https://app.travis-ci.com/github/conda-forge/numpy-feedstock/jobs/594324445)

**Comment by h-vetinari** [comment]
With the appearance of 1.25, I'm closing this

**Pull request closed without merging**
