### PR TITLE
recompile

### PR DESCRIPTION
**Pull request by marcelotrevisani**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by marcelotrevisani** [comment]
@conda-forge-admin please rerender

**Comment by rgommers** [comment]
@marcelotrevisani could you comment on what changes with this rebuild?

**Comment by h-vetinari** [comment]
Presumably the packages compiled with GCC 7 are not installable anymore with those by compiled by GCC 9 (not due to GCC but due to changes in the cf compiler infra around that time). But 1.15 is really old... The global pinning is at 1.18 already.

**Comment by marcelotrevisani** [comment]
Sorry, I was doing some tests, that is not needed anymore, I will close it :)

Thanks for all the messages

**Pull request closed without merging**
