### PR TITLE
Windows support

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by isuruf** [comment]
Tests pass on windows.
cc @conda-forge/core, @xoviat, @conda-forge/scipy, thought you might be interested

**Comment by xoviat** [comment]
Suprised that conda-forge had no numpy before.

**Comment by xoviat** [comment]
Numpy is like the foundation of scientific computing, which is what conda advertises itself as.

**Comment by isuruf** [comment]
@xoviat, we were using numpy from the defaults channel before. (Compiled with ifort and mkl)

**Comment by xoviat** [comment]
Actually can you apply the flang PR patch?

**Comment by isuruf** [comment]
> Do you have any thought on the compatibility between packages compiled with flang and those compiled with ifort? 

We think `flang` and `ifort` compiled packages will be interoperable.

> Specifically if someone created an environment with a flang/openblas compiled NumPy from conda-forge and the ifort/MKL SciPy from defaults would there be problems? Is it even possible to create such an environment without using --force?

I don't think there would be problems. PyPI wheels mix libraries that way. Numpy is compiled with MSVC/Atlas. Scipy is compiled with MSVC/gfortran/openblas. (I think next numpy release is going to switch to openblas) It is possible to create such an environment.

What'll be interesting is to see compiling scipy with ifort and flang-compiled-openblas. We already know that scipy with flang and mkl almost works (except for 4/10000 tests failing).

@jjhelmus, do you have access to ifort? Would you mind compiling numpy like this PR and compiling scipy with openblas and ifort?

**Comment by jjhelmus** [comment]
I do have access to ifort.  It might be a few days before I have some free time but I'll test a few different permutations of NumPy, SciPy, compilers, BLAS libraries and report back.

**Comment by jakirkham** [comment]
Might also want to experiment with some of the older versions of NumPy as well. This is kind of important as I believe everything is building against rather old versions of NumPy for Windows. Admittedly this will be a bit of a patch job to get right.

**Comment by xoviat** [comment]
@jakirkham As expected, the OpenBLAS build released on conda-forge turned out to be buggy. This is not a problem because OpenBLAS doesn't override defaults. However, we cannot release numpy at this time because that will override the default numpy and give people a nasty surprise.

**Comment by xoviat** [comment]
To be clear, the bugs are compiler bugs in flang. They will be fixed eventually.

**Pull request closed without merging**
