### PR TITLE
Build numpy 1.11 for windows 64 bit

### PR DESCRIPTION
**Pull request by hmaarrfk**
Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` conda-forge-admin, please rerender
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
@conda-forge/numpy @conda-forge/core is there a reason why numpy is still skipped on pyk3 windows today? seems to compile and pass tests

**Comment by scopatz** [comment]
Not sure, best to ask @conda-forge/numpy

**Comment by rgommers** [comment]
> is there a reason why numpy is still skipped on pyk3 windows today?

There are 64-bit Windows binaries, the skip is `# [win32 or (win and py27)]`. I think that's because there are only 64-bit OpenBLAS builds for Windows.

**Comment by hmaarrfk** [comment]
I guess I should have been more clear, for numpy 1.11.

Many recipes use pin to an older numpy, this is a backport of that. I'll modify the recipe with the skip in Master.

**Comment by hmaarrfk** [comment]
@conda-forge-admin, please rerender

**Pull request closed without merging**
