### PR TITLE
Don't set libraries entry in DEFAULT

### PR DESCRIPTION
**Pull request by isuruf**
Otherwise, even for libraries like fftw will get blas,cblas,lapack

Fixes https://github.com/conda-forge/numpy-feedstock/issues/201

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by isuruf** [comment]
@rgommers, thoughts?

**Comment by rgommers** [comment]
Thanks @isuruf. This looks good to me, seems safe and if it fixes the problem then should be good to merge. That said, I'm not familiar with what `recipe.bat` does exactly. The normal way these settings propagate is the defaults in `numpy/distutils/system_info.py`, which can be overridden with a `site.cfg` file. It seems `recipe.bat` overrides those somehow?

**Comment by isuruf** [comment]
Yes, `recipe/bld.bat` creates a `site.cfg` with the paths and library names.

**Comment by isuruf** [comment]
Thanks for the review

**Pull request merged**
