### PR TITLE
Rerender with python 3.7 enabled

### PR DESCRIPTION
**Pull request by jschueller**

### CODE REVIEW

**Comment by jschueller** [comment]
Setting CF_MAX_PY_VER=37 env var does not seem to work, had to manually edit conda_build_config.yaml.
Do we want to drop py35 ?

**Comment by ocefpaf** [comment]
> Setting CF_MAX_PY_VER=37 env var does not seem to work, had to manually edit 

I guess there are some extra vars one must set. Ping @CJ-Wright 

> conda_build_config.yaml.

Let me re-do this PR with my "hacked" conda-smithy. I had another change I want to test which removes `defaults` from the build.

> Do we want to drop py35 ?

Not yet, only when we move the whole stack to py37.

**Comment by CJ-Wright** [comment]
That env var needs to be set in https://github.com/conda-forge/numpy-feedstock/blob/master/conda-forge.yml see: https://github.com/conda-forge/openlibm-feedstock/pull/6/files#diff-c48034b662d2a516a39beb01e6a756dfR4

**Comment by ocefpaf** [comment]
> That env var needs to be set in https://github.com/conda-forge/numpy-feedstock/blob/master/conda-forge.yml see: https://github.com/conda-forge/openlibm-feedstock/pull/6/files#diff-c48034b662d2a516a39beb01e6a756dfR4

Ah, OK. Good to know! But this does make things a little hard to do it manually.

**Comment by jschueller** [comment]
Yes, how do I do that manually ?

**Comment by CJ-Wright** [comment]
Could you add the env vars to the conda-forge.yml?

**Comment by ocefpaf** [comment]
> Could you add the env vars to the conda-forge.yml?

In theory we should not really encourage doing it manually unless it is really needed. We must focus on the compiler migration first to avoid duplicated effort and ending up with two incompatible ecosystems of Python 3.7 binaries.

(I am guilt of most of the PY37 PRS though :flushed:, but still I do not encourage people to do it unless it is extremelly necessary. Let's wait for the migrator!)

**Comment by ocefpaf** [comment]
> What's happening with the compilers ?

We are moving to new compilers and the new packages won't be compatible with the old ones. So we are "migrating" to the new compilers and Python 3.7 (and R 3.5) in one go to avoid re-building stuff multiple times.

**Pull request closed without merging**
