### PR TITLE
Backport msvccompiler patch

### PR DESCRIPTION
**Pull request by jschueller**
see https://github.com/numpy/numpy/issues/27405
@conda-forge-admin please rerender

### CODE REVIEW

**Comment by jschueller** [comment]
@conda-forge-admin please rerender

**Comment by jschueller** [comment]
@conda-forge-admin please rerender

**Review by h-vetinari — CHANGES_REQUESTED** [review]
See my [comment](https://github.com/conda-forge/assimulo-feedstock/pull/109#issuecomment-2449313736) in the assimulo PR. It should be patched there, not in numpy

**Comment by rgommers** [comment]
I see no problem in applying this patch, it can only help and apparently is tripping up a lot of people. Why not merge this?

**Comment by h-vetinari** [comment]
> I see no problem in applying this patch, it can only help and apparently is tripping up a lot of people. Why not merge this?

I said as much in https://github.com/conda-forge/assimulo-feedstock/pull/109, though https://github.com/numpy/numpy/issues/27405 got rejected too to be fair.

**Comment by rgommers** [comment]
> though [numpy/numpy#27405](https://github.com/numpy/numpy/issues/27405) got rejected too to be fair.

Only at first, it was quickly reopened and fixed via PR 2 days later (https://github.com/numpy/numpy/pull/27406).

**Pull request closed without merging**
