### PR TITLE
Manual pypy3.7 migration build

### PR DESCRIPTION
**Pull request by h-vetinari**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

I was wondering why https://github.com/conda-forge/pandas-feedstock/pull/106 had been opened by the migrator already, and couldn't find `numpy` listed anywhere in the [migration page](https://conda-forge.org/status/). Trying a manual build, but happy to close if this should be done differently.

### CODE REVIEW

**Comment by h-vetinari** [comment]
Depends (at least) on https://github.com/conda-forge/pytest-feedstock/pull/132

**Comment by hmaarrfk** [comment]
Seems like there is a missing dependency on aarch.

**Comment by h-vetinari** [comment]
Nope, that's just because drone didn't pick up the restart.

**Comment by isuruf** [comment]
cc @conda-forge/bot, was there any code added to the bot to skip any packages in the migration yaml itself? Looks like the bot is skipping numpy for this migration

**Comment by h-vetinari** [comment]
There's a ppc build that [failed](https://github.com/conda-forge/numpy-feedstock/runs/1678453074) on master - could some one restart it?

**Pull request merged**
