### PR TITLE
Numpy115 migration

### PR DESCRIPTION
**Pull request by hmaarrfk**
Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
@jjhelmus do you have time to look at some of the failures here related toe ppc64le?

If you have limited time, this seems like the best version to run with if we want to continue with the migration. numy 1.16 seems to have really weird compiler related failures that I can't understand.

Other versions might be too old?

aarch64 is passing numpy 1.11 through 1.15 except 1.13

**Comment by isuruf** [comment]
@jayfurmanek, do you have some time to help?

**Comment by jayfurmanek** [comment]
Hi! This is awesome! ..well the fails are not but the fact that ya'll got this going is awsome!
I'll take a look, or I'll bug someone on my team to. We'd love to see this going. 
I'll look now and see if I can understand whats happening.

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Comment by hmaarrfk** [comment]
@jjhelmus @conda-forge-arm any interest in continuing here?

**Comment by hmaarrfk** [comment]
I suspect that we should test this on real hardware.

**Comment by mariusvniekerk** [comment]
Looks like  aarch64 works!

**Comment by hmaarrfk** [comment]
Yeah, aarch64 works on quite a few versions of numpy. I had to add a patch remember. I just think we can either get this version to work for PPC64LE

Optionally, we can try to get numpy 1.16 to work.

**Comment by mariusvniekerk** [comment]
we should be able to get numpy 1.16 alive.  This at least can open up some of the rest

**Comment by hmaarrfk** [comment]
Once we start compiling with numpy 1.15, I won't want to go backward and support older numpy. I guess we can address the problematic recipes as they come. Feel free to try 1.16. IT was just crashing with me.

**Comment by isuruf** [comment]
> Once we start compiling with numpy 1.15, I won't want to go backward and support older numpy. 

Agree. I would say not to support python 2.7 either as numpy support is already dropped and will be EOL in less than a year.

**Comment by hmaarrfk** [comment]
supporting 2.7 is not creating a roadblock at the moment.

I think we can leave it in until it causes problems.

If it causes any hiccups, just drop it.

**Comment by mariusvniekerk** [comment]
@isuruf our general model for py27 in these arches has been "if it works great, but no additional work will be done to make it function for legacy python"

**Comment by hmaarrfk** [comment]
@mariusvniekerk MAGIC. Travis has PPC64LE?

**Comment by mariusvniekerk** [comment]
@hmaarrfk yep it does actually

**Comment by hmaarrfk** [comment]
I really want to avoid the case where:

"
My recipe works because I compile with numpy 1.11.
Now that you compile with numpy 1.15 it won't work anymore.
"

That was my motivation behind making older numpys work.
Recipes that work with
```
run:
- numpy 1.11
```
won't have to get changed.

**Comment by hmaarrfk** [comment]
Can I request that we try older numpys now too? And at least give them a little bit of elbow grease with this new (to me) revelation?

**Comment by hmaarrfk** [comment]
@mariusvniekerk @jjhelmus it seems to be hanging randomly on aarch64 using qemu.

@mariusvniekerk maybe we should formalize a shippable container for this?

**Comment by hmaarrfk** [comment]
lets close in favour of moving on.

**Pull request closed without merging**
