### PR TITLE
Numpy 1.20.3 (redux)

### PR DESCRIPTION
**Pull request by h-vetinari**
Cannot commit into #232 so separate PR to skip the newly failing test.

Closes #232

### CODE REVIEW

**Comment by h-vetinari** [comment]
So the Py39 run on travis failed (apparently) on a test that was not previously skipped:
`lib/tests/test_format.py::test_empty_npz`

Someone might try if a restart fixes things. Otherwise happy to readd skips, I just found in #227 that most of these skips are obsolete by now, so it should be part of routine hygiene to clean them up once in a while...

**Comment by h-vetinari** [comment]
Mahgahd, it's so annoying that mere contributors cannot restart CI jobs directly - which leaves just pointlessly opening & closing or pushing new commits.

**Comment by h-vetinari** [comment]
> Mahgahd, it's so annoying that mere contributors cannot restart CI jobs directly

... especially with the number of connection problems that travis is having. 😒

**Comment by h-vetinari** [comment]
Finally this is turning green @conda-forge/numpy - there were no more flaky tests with travis, just lots of random http timeouts.

**Comment by h-vetinari** [comment]
Ping @conda-forge/numpy, this should be good to go - would be nice to have 1.20.3 available 🙃

**Review by rgommers — APPROVED** [review]
Skipped test changes all LGTM, and CI is green. Thanks @h-vetinari

**Comment by h-vetinari** [comment]
Thanks @rgommers

One build on travis needs restarting:
```
[...]
core/tests/test_indexing.py::TestCApiAccess::test_getitem PASSED         [ 13%]
core/tests/test_indexing.py::TestCApiAccess::test_setitem PASSED   

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received

The build has been terminated
```

Also, pypy on aarch failed through having a crashed worker, so probably worth a restart too.
```
=================================== FAILURES ===================================
_________________________ core/tests/test_datetime.py __________________________
[gw47] linux -- Python 3.7.10 $PREFIX/bin/python
worker 'gw47' crashed while running 'core/tests/test_datetime.py::TestDateTime::test_limit_str_roundtrip[1-W]'
=============================== warnings summary ===============================
```

**Comment by rgommers** [comment]
No luck.

**Pull request merged**
