### PR TITLE
Switch to gcc on linux-aarch64

### PR DESCRIPTION
**Pull request by jjhelmus**
Compiler bug which required the use of clang has been resolved in gcc 7.5.0

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jjhelmus** [comment]
@conda-forge-admin, please rerender

**Comment by isuruf** [comment]
@rgommers,do you know the reason for the failure,

```
2020-08-03T02:46:58.8028285Z =================================== FAILURES ===================================
2020-08-03T02:46:58.8032486Z _____________________________ test_api_importable ______________________________
2020-08-03T02:46:58.8033207Z 
2020-08-03T02:46:58.8033733Z     def test_api_importable():
2020-08-03T02:46:58.8034240Z         """
2020-08-03T02:46:58.8034825Z         Check that all submodules listed higher up in this file can be imported
2020-08-03T02:46:58.8035391Z     
2020-08-03T02:46:58.8035962Z         Note that if a PRIVATE_BUT_PRESENT_MODULES entry goes missing, it may
2020-08-03T02:46:58.8036658Z         simply need to be removed from the list (deprecation may or may not be
2020-08-03T02:46:58.8037916Z         needed - apply common sense).
2020-08-03T02:46:58.8038462Z         """
2020-08-03T02:46:58.8038984Z         def check_importable(module_name):
2020-08-03T02:46:58.8039544Z             try:
2020-08-03T02:46:58.8040076Z                 importlib.import_module(module_name)
2020-08-03T02:46:58.8040729Z             except (ImportError, AttributeError):
2020-08-03T02:46:58.8041291Z                 return False
2020-08-03T02:46:58.8041764Z     
2020-08-03T02:46:58.8042213Z             return True
2020-08-03T02:46:58.8042678Z     
2020-08-03T02:46:58.8043127Z         module_names = []
2020-08-03T02:46:58.8043690Z         for module_name in PUBLIC_MODULES:
2020-08-03T02:46:58.8044301Z             if not check_importable(module_name):
2020-08-03T02:46:58.8044919Z                 module_names.append(module_name)
2020-08-03T02:46:58.8045426Z     
2020-08-03T02:46:58.8045899Z         if module_names:
2020-08-03T02:46:58.8046491Z             raise AssertionError("Modules in the public API that cannot be "
2020-08-03T02:46:58.8047176Z                                  "imported: {}".format(module_names))
2020-08-03T02:46:58.8047788Z     
2020-08-03T02:46:58.8048310Z         for module_name in PUBLIC_ALIASED_MODULES:
2020-08-03T02:46:58.8049853Z             try:
2020-08-03T02:46:58.8050358Z                 eval(module_name)
2020-08-03T02:46:58.8050918Z             except AttributeError:
2020-08-03T02:46:58.8051488Z                 module_names.append(module_name)
2020-08-03T02:46:58.8051999Z     
2020-08-03T02:46:58.8052464Z         if module_names:
2020-08-03T02:46:58.8053076Z             raise AssertionError("Modules in the public API that were not "
2020-08-03T02:46:58.8053765Z                                  "found: {}".format(module_names))
2020-08-03T02:46:58.8054331Z     
2020-08-03T02:46:58.8054875Z         with warnings.catch_warnings(record=True) as w:
2020-08-03T02:46:58.8056607Z             warnings.filterwarnings('always', category=DeprecationWarning)
2020-08-03T02:46:58.8057582Z             warnings.filterwarnings('always', category=ImportWarning)
2020-08-03T02:46:58.8058303Z             for module_name in PRIVATE_BUT_PRESENT_MODULES:
2020-08-03T02:46:58.8058973Z                 if not check_importable(module_name):
2020-08-03T02:46:58.8059619Z                     module_names.append(module_name)
2020-08-03T02:46:58.8060713Z     
2020-08-03T02:46:58.8065205Z         if module_names:
2020-08-03T02:46:58.8065799Z             raise AssertionError("Modules that are not really public but looked "
2020-08-03T02:46:58.8066391Z                                  "public and can not be imported: "
2020-08-03T02:46:58.8066910Z >                                "{}".format(module_names))
2020-08-03T02:46:58.8068169Z E           AssertionError: Modules that are not really public but looked public and can not be imported: ['numpy.distutils.command.develop', 'numpy.distutils.command.egg_info']
2020-08-03T02:46:58.8068987Z 
2020-08-03T02:46:58.8070328Z ../_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.6/site-packages/numpy/tests/test_public_api.py:490: AssertionError
```

**Comment by rgommers** [comment]
Hmm, that is very odd. I can't think of a reason why
```
['numpy.distutils.command.develop', 'numpy.distutils.command.egg_info']
```
would not be importable while the other `command`s are importable.

Perhaps due to `setuptools` 0.49`, that vendored `distutils` and I believe we have it currently blacklisted in NumPy's CI because things are broken. From looking at one TravisCI log, it uses that `setuptools` version. This failure is harmless though, if the build works and other tests pass.

**Comment by isuruf** [comment]
@rgommers, looks like we had `setuptools` pulled in indirectly in test phase and it was dropped by some dependency. Adding `setuptools` as a direct dependency in `test` phase fixed it.

**Comment by jjhelmus** [comment]
The `linux_aarch64_numpy1.18python3.6.____73_pypy` drone job is timing out after 1 hour, the other jobs pass.

**Comment by isuruf** [comment]
Restarting it should fix it

**Pull request merged**
