### PR TITLE
Numpy114 migration

### PR DESCRIPTION
**Pull request by hmaarrfk**
@conda-forge/arm-arch 
Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
There are many bad failures here regarding non-standard datatype.

**Comment by hmaarrfk** [comment]
Closing in favour of moving on.

**Comment by xhochy** [comment]
@hmaarrfk What was the solution here? Use a newer numpy for Aarch64 builds?

**Comment by hmaarrfk** [comment]
Yeah. At this point it seems there is not enough collective bandwidth to get these scientific packages through. 

We changed the default numpy pinning to 1.16 for aarch and ppc64le.
Older numpy was even more buggy with these bug endian machines anyway

**Pull request closed without merging**
